[package]
description = "An experimental Tauri Plugin for Sentry"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "sentry-tauri"
readme = "README.md"
repository = "https://github.com/timfish/sentry-tauri"
version = "0.1.0"

[dependencies]
sentry = "0.27"
sentry-rust-minidump = "0.1"
serde = "1"
tauri = "1"
thiserror = "1"
crash-context = "0.4"
